spring:
  application:
    name: account-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/pricedepo-account
    username: pricedepo
    password: pricedepo

server:
  port: ${PORT:8080}
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true


---

spring:
  profiles: test
  
#keep this test property for Context testing
test:
  property: test